title: HEP Arxiv Daily
description: Automatically Update HEP Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/HJW-2021/HEP-arxiv-daily
  another_url: https://github.com/HJW-2021/HEP-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  E-mail: wanghongjian16@lzu.edu.cn
  github: HJW-2021

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
